name: Docker Image Publish

on:
  push:
    branches: ["main"]
    paths:
      - "**.Dockerfile"

jobs:
  # Docs: https://github.com/marketplace/actions/changed-files
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: "**.Dockerfile"
          since_last_remote_commit: true
          matrix: true

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  build:
    needs: [changed-files]
    strategy:
      matrix:
        ImageName: ${{ fromJSON(needs.changed-files.outputs.matrix) }}

    with:
      DOCKERFILE_PATH: ${{ matrix.ImageName }}
    secrets: inherit
    uses: ./.github/workflows/build-and-publish-container.yml
