name: Build all images

on: workflow_dispatch

jobs:
  # Docs: https://github.com/mirko-felice/list-files-action
  lookup:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-files.outputs.paths }}
    steps:
      - name: List Files
        id: list-files
        uses: mirko-felice/list-files-action@v3.0.5
        with:
          repo: ${{ github.repository }}
          ref: ${{ github.ref }}
          path: "."
          ext: ".Dockerfile"

  build:
    needs: [lookup]
    strategy:
      matrix:
        ImageName: ${{ fromJSON(needs.lookup.outputs.paths) }}

    with:
      DOCKERFILE_PATH: ${{ matrix.ImageName }}
    secrets: inherit
    permissions:
      packages: write
      id-token: write
      contents: read
    uses: ./.github/workflows/build-and-publish-container.yml
